//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTI.Modules.SecurityCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTI.Modules.SecurityCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The staff&apos;s Account lock status is not saved.
        /// </summary>
        internal static string AccountLockedError {
            get {
                return ResourceManager.GetString("AccountLockedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current position cannot be inactivated due to staff currently assigned that position..
        /// </summary>
        internal static string activitySettingError {
            get {
                return ResourceManager.GetString("activitySettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Center.
        /// </summary>
        internal static string assemblyTitle {
            get {
                return ResourceManager.GetString("assemblyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BG00 {
            get {
                object obj = ResourceManager.GetObject("BG00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BG01 {
            get {
                object obj = ResourceManager.GetObject("BG01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BG02 {
            get {
                object obj = ResourceManager.GetObject("BG02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueButtonDown {
            get {
                object obj = ResourceManager.GetObject("BlueButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueButtonUp {
            get {
                object obj = ResourceManager.GetObject("BlueButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout from the machine?.
        /// </summary>
        internal static string ConfirmLogOut {
            get {
                return ResourceManager.GetString("ConfirmLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine logout.
        /// </summary>
        internal static string ConfirmLogoutTitle {
            get {
                return ResourceManager.GetString("ConfirmLogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of .
        /// </summary>
        internal static string CopyOf {
            get {
                return ResourceManager.GetString("CopyOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save permission changes?.
        /// </summary>
        internal static string DoYouWantToSaveCase1 {
            get {
                return ResourceManager.GetString("DoYouWantToSaveCase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save activity changes?.
        /// </summary>
        internal static string DoYouWantToSaveCase2 {
            get {
                return ResourceManager.GetString("DoYouWantToSaveCase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save activity and permission changes?.
        /// </summary>
        internal static string DoYouWantToSaveCase3 {
            get {
                return ResourceManager.GetString("DoYouWantToSaveCase3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Position.
        /// </summary>
        internal static string EditPosition {
            get {
                return ResourceManager.GetString("EditPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Staff.
        /// </summary>
        internal static string EditStaff {
            get {
                return ResourceManager.GetString("EditStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load View Staff.
        /// </summary>
        internal static string errorFailedLoadInitStaff {
            get {
                return ResourceManager.GetString("errorFailedLoadInitStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save position.
        /// </summary>
        internal static string errorFailedSavePosition {
            get {
                return ResourceManager.GetString("errorFailedSavePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the staff.
        /// </summary>
        internal static string errorFailedSaveStaff {
            get {
                return ResourceManager.GetString("errorFailedSaveStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The staff&apos;s login number is duplicate, Please use another login number.
        /// </summary>
        internal static string errorFailedSaveStaffDup {
            get {
                return ResourceManager.GetString("errorFailedSaveStaffDup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get data.
        /// </summary>
        internal static string errorFailedToGetData {
            get {
                return ResourceManager.GetString("errorFailedToGetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save position&apos;s modules and features .
        /// </summary>
        internal static string errorFailedToSaveModuleFeatures {
            get {
                return ResourceManager.GetString("errorFailedToSaveModuleFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : .
        /// </summary>
        internal static string errorGeneral {
            get {
                return ResourceManager.GetString("errorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number can be number, space or  &quot;-&quot;.
        /// </summary>
        internal static string errorInvalidPhoneNumber {
            get {
                return ResourceManager.GetString("errorInvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Parse Settings.
        /// </summary>
        internal static string errorParse {
            get {
                return ResourceManager.GetString("errorParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run when loading data.
        /// </summary>
        internal static string errorRun {
            get {
                return ResourceManager.GetString("errorRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error, application is being closed now.
        /// </summary>
        internal static string errorStart {
            get {
                return ResourceManager.GetString("errorStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected behavior.
        /// </summary>
        internal static string errorUnexpected {
            get {
                return ResourceManager.GetString("errorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve operator information from the server.  Reason: {0}.
        /// </summary>
        internal static string GetOperatorDataFailed {
            get {
                return ResourceManager.GetString("GetOperatorDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve your staff information from the server.  Reason: {0}.
        /// </summary>
        internal static string GetStaffDataFailed {
            get {
                return ResourceManager.GetString("GetStaffDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve your permissions from the server. Reason: {0}.
        /// </summary>
        internal static string GetStaffPermsFailed {
            get {
                return ResourceManager.GetString("GetStaffPermsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save change? .
        /// </summary>
        internal static string infoSaveChange {
            get {
                return ResourceManager.GetString("infoSaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} response received from server..
        /// </summary>
        internal static string InvalidMessageResponse {
            get {
                return ResourceManager.GetString("InvalidMessageResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        internal static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} message payload is the wrong size..
        /// </summary>
        internal static string MessagePayloadWrongSize {
            get {
                return ResourceManager.GetString("MessagePayloadWrongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords must be {0} or more characters in length.
        /// </summary>
        internal static string MinimumPasswordLength {
            get {
                return ResourceManager.GetString("MinimumPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Modules.
        /// </summary>
        internal static string modulesAll {
            get {
                return ResourceManager.GetString("modulesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords must be {0} or more characters in length and must be different than any of the previous {1} passwords..
        /// </summary>
        internal static string MPasswordReuseError {
            get {
                return ResourceManager.GetString("MPasswordReuseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Position.
        /// </summary>
        internal static string NewPosition {
            get {
                return ResourceManager.GetString("NewPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Position Name.
        /// </summary>
        internal static string NewPositionName {
            get {
                return ResourceManager.GetString("NewPositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Staff.
        /// </summary>
        internal static string NewStaff {
            get {
                return ResourceManager.GetString("NewStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should meet minimum complexity settings.
        /// </summary>
        internal static string PasswordComplexitySetting {
            get {
                return ResourceManager.GetString("PasswordComplexitySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords must be different than any of the previous {0} passwords..
        /// </summary>
        internal static string PasswordReuseError {
            get {
                return ResourceManager.GetString("PasswordReuseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords must be {0} or more characters in length and must be different than any of the previous {1} passwords. Further, passwords must contain at least two of the four character groups: English upper case letters (A-Z).                
        ///    Numerals (0-9).                 
        ///             English lower case letters (a-z). 
        ///                                                 Non-alphabetic characters (i.e. !, #, $, @, %, ^, +, =).
        ///                                             All passwords expire {2} days  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Passwords {
            get {
                return ResourceManager.GetString("Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string PermissionLevel0 {
            get {
                return ResourceManager.GetString("PermissionLevel0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string PermissionLevel1 {
            get {
                return ResourceManager.GetString("PermissionLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        internal static string PermissionLevel2 {
            get {
                return ResourceManager.GetString("PermissionLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a staff for editing.
        /// </summary>
        internal static string Pleaseselectstaff {
            get {
                return ResourceManager.GetString("Pleaseselectstaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Center.
        /// </summary>
        internal static string securityCenter {
            get {
                return ResourceManager.GetString("securityCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Center.
        /// </summary>
        internal static string SecurityCenterName {
            get {
                return ResourceManager.GetString("SecurityCenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server communication lost..
        /// </summary>
        internal static string ServerCommFailed {
            get {
                return ResourceManager.GetString("ServerCommFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server returned error code: {0}.
        /// </summary>
        internal static string ServerErrorCode {
            get {
                return ResourceManager.GetString("ServerErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Module Level Data ....
        /// </summary>
        internal static string splashInfoLoadModuleLevelData {
            get {
                return ResourceManager.GetString("splashInfoLoadModuleLevelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading All Staff Data ....
        /// </summary>
        internal static string splashInfoLoadStaffPositionModule {
            get {
                return ResourceManager.GetString("splashInfoLoadStaffPositionModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Station Settings ....
        /// </summary>
        internal static string splashInfoLoadStationSettings {
            get {
                return ResourceManager.GetString("splashInfoLoadStationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff not found..
        /// </summary>
        internal static string StaffNotFound {
            get {
                return ResourceManager.GetString("StaffNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Center -- FortuNet, Inc..
        /// </summary>
        internal static string titleSecurityCenter {
            get {
                return ResourceManager.GetString("titleSecurityCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Staff.
        /// </summary>
        internal static string ViewStaff {
            get {
                return ResourceManager.GetString("ViewStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Waiting {
            get {
                object obj = ResourceManager.GetObject("Waiting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel your change?.
        /// </summary>
        internal static string warningCancel {
            get {
                return ResourceManager.GetString("warningCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth is after the hire date.
        /// </summary>
        internal static string warningDOBAfterDateOfHire {
            get {
                return ResourceManager.GetString("warningDOBAfterDateOfHire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Login Number is not allowed, please choose a new Login Number.
        /// </summary>
        internal static string warningDupLoginNumber {
            get {
                return ResourceManager.GetString("warningDupLoginNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate magnetic card is not allowed, please choose a new magnetic card.
        /// </summary>
        internal static string warningDupMagCard {
            get {
                return ResourceManager.GetString("warningDupMagCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required for a new staff.
        /// </summary>
        internal static string warningPasswordBeforeSave {
            get {
                return ResourceManager.GetString("warningPasswordBeforeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match!.
        /// </summary>
        internal static string warningPasswordNotSame {
            get {
                return ResourceManager.GetString("warningPasswordNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position name can not be empty or duplicate.
        /// </summary>
        internal static string warningPositionName {
            get {
                return ResourceManager.GetString("warningPositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete required fields in order to save the staff correctly.
        /// </summary>
        internal static string warningRequiredFiledBeforeSave {
            get {
                return ResourceManager.GetString("warningRequiredFiledBeforeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your change?.
        /// </summary>
        internal static string warningSave {
            get {
                return ResourceManager.GetString("warningSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify password before saving.
        /// </summary>
        internal static string warningverifyingPassword {
            get {
                return ResourceManager.GetString("warningverifyingPassword", resourceCulture);
            }
        }
    }
}
